name: Example
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      - uses: getong/mariadb-action@v1.1
        with:
          mysql database: "example"
          mysql root password: "pass"
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: .
          args: |
            validate
            push
            deploy
          working-directory: example
        env:
          DATABASE_URL: mysql://root:pass@localhost:3306/example
      - name: Run Dagger Pipelines
        run: dagger run deno run -A ../src/dagger/runner.ts
        working-directory: example
        env:
          DATABASE_URL: mysql://root:pass@mysql:3306/example
